In [ ]:
def def_images(list):
    global images
    images = np.zeros(0)

    for i in range(len(list)):
        images[i] = image.imread(list[i])
        
    

In [ ]:
def_images()

In [1]:
# Librerías necesarias
import cv2
import os
import pathlib
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import image
from mpl_toolkits.axes_grid1 import ImageGrid


In [2]:
# Creación de la lista de directorios
parent_original = "A:/FoFi-Detection/dataset/fire/"
os.chdir(parent_original)
list_original = os.listdir(parent_original)
del list_original[0]

# print(list_original[0])


In [4]:
labels = np.zeros((25,), dtype=int)
# print(labels)
for i in range(len(list_original)):
    # Creación de la lista de sub directorios para mostrar las subimagenes
    os.chdir(parent_original)
    parent_sub = "A:/FoFi-Detection/dataset/sub_fire_images/"+list_original[i][:-4]+"_dir"
    # print(parent_sub)
    img_original = cv2.imread(list_original[i])
    title_window_original = "original "+str(i)+'/'+str(len(list_original))
    cv2.putText(img=img_original, text=title_window_original, org=(10, 10), fontFace=cv2.FONT_HERSHEY_DUPLEX, fontScale=.4, color=(0, 255, 0),thickness=1)
    cv2.imshow("original", img_original)
    cv2.moveWindow("original",40,30)
    # cv2.waitKey(0)
    # Cambiamos al subfolder
    os.chdir(parent_sub)
    list_sub = os.listdir(parent_sub)
    # print(list_sub)
    
    # subimagenes
    # arreglo de etiquetados (1 para cad asubfolder, después se concatenará)
    
    for j in range(len(list_sub)):
        img_sub = cv2.imread(list_sub[j])
        cv2.imshow("sub", img_sub)
        cv2.moveWindow("sub",300,30)
        k = cv2.waitKey(0)
        """
            1 = Fuego
            2 = No fuego
            3 = Humo
        """
        if k == 49: 
            labels[j]=1
        elif k == 50:
            labels[j]=2
        elif k == 51:
            labels[j]=3
        else:
            # Detectar incorrectos en el txt
            labels[j]=-1
    
    # Write array to a txt file
    txt_name = list_original[i][:-4] + '_labels.txt'
    print(labels)
    print('saving data on: '+ parent_sub + ' as ' + txt_name )
    np.savetxt(txt_name,labels,fmt='%d')
    
    

[1 1 1 1 1 2 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 3 1]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fire_0001_dir as fire_0001_labels.txt
[1 2 2 2 1 1 2 1 2 1 2 1 2 1 2 1 2 1 1 2 1 2 1 2 1]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fire_0002_dir as fire_0002_labels.txt
[2 1 2 1 2 3 1 3 1 3 2 1 3 2 1 3 2 1 3 2 1 2 3 2 1]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fire_0003_dir as fire_0003_labels.txt
[3 2 1 2 3 2 2 1 3 2 1 2 2 3 2 1 2 1 2 3 2 1 2 1 2]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fire_0004_dir as fire_0004_labels.txt
[2 3 2 1 2 1 2 1 3 2 1 2 1 2 1 3 2 1 2 1 3 2 1 2 2]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fire_0006_dir as fire_0006_labels.txt
[1 1 2 3 2 1 2 2 1 3 2 1 2 3 2 1 2 2 1 2 3 2 1 2 3]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fire_0007_dir as fire_0007_labels.txt
[1 2 3 2 1 2 3 2 1 2 3 2 2 3 2 1 2 3 2 1 2 3 2 1 2]
saving data on: A:/FoFi-Detection/dataset/sub_fire_images/fi

KeyboardInterrupt: 

In [ ]:
os.chdir(parent_original)

In [ ]:
dir_list_original = os.listdir(parent_original)
del dir_list_original[0] # Eliminamos checkpoint de jupyter
# print(dir_list_original)

In [ ]:
for i in range(len(dir_list_original)):
    os.chdir(parent_original)
    parent_sub = "A:/FoFi-Detection/dataset/sub_fire_images"
    path_sub = parent_sub + dir_list_original[:-4]+'_dir'
    dir_list_sub = os.listdir
    # Matplot code
    def_images()
    
    #######
    
    fig = plt.figure(figsize(8.,8.))
    grid = ImageGrid(fig, 111,
                    nrows_ncols=(2, 2),
                    axes_pad = 0.1
                    )
    for ax, im in zip(grid,images):
        ax.imshow(im)
        
    plt.show()
    # img1 = cv2.imread(dir_list_original[i])
    # cv2.imshow('Original',img1)
    
    parent_sub = "A:/FoFi-Detection/dataset/sub_fire_images/"+dir_list_original[i][:-4]+'_dir'
    os.chdir(parent_sub)
    
    dir_list_sub = os.listdir(parent_sub)
    
    for j in range(len(dir_list_sub)):
        img2 = cv2.imread(dir_list_sub[j])
        cv2.imshow('Subimage',img2)
        cv2.waitKey(0)
        cv2.destroyAllWindows()               